//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MASCOTA
    {
        public int IdMascota { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdDueno { get; set; }
        public int IdTipo { get; set; }
    
        public virtual TBL_DUENO TBL_DUENO { get; set; }
        public virtual TBL_TIPO_MASCOTA TBL_TIPO_MASCOTA { get; set; }
    }
}
